import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/**
 * Node builtins the Azure Speech SDK requires at module scope.
 *
 * `ConsoleLoggingListener` and `AudioFileWriter` pull in `fs`; the websocket
 * adapter pulls in `net`/`tls` for its Node transport. None of them run in the
 * paths this plugin uses, but a bare `require("fs")` still executes on load —
 * which on Obsidian mobile, where there is no Node, throws before the plugin
 * can start. Leaving them merely `external` is what makes a mobile-capable
 * manifest a lie.
 */
const OPTIONAL_NODE_MODULES = ["fs", "net", "tls"];

/**
 * Resolve those modules to a guarded shim: the real module on desktop, an empty
 * object where Node is absent. `req` is an indirect binding so esbuild cannot
 * statically rewrite it back into a bundled require, which would recurse.
 */
const optionalNodeShim = {
	name: "optional-node-shim",
	setup(build) {
		const filter = new RegExp(`^(${OPTIONAL_NODE_MODULES.join("|")})$`);

		build.onResolve({ filter }, (args) => ({
			path: args.path,
			namespace: "optional-node",
		}));

		build.onLoad({ filter: /.*/, namespace: "optional-node" }, (args) => ({
			contents: `
				const req = typeof require === "function" ? require : null;
				let mod = {};
				if (req) {
					try { mod = req(${JSON.stringify(args.path)}); } catch (e) { mod = {}; }
				}
				module.exports = mod;
			`,
			loader: "js",
		}));
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins.filter((m) => !OPTIONAL_NODE_MODULES.includes(m)),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	outfile: "main.js",
	plugins: [optionalNodeShim],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
